localization = {
    languages = [
        {
            code = "ru",
            name = "Русский"
            task-status = {
                "in-progress": "В работе"
                "planned": "Запланировано"
                "backlog": "Бэклог"
                "completed": "Завершено"
            }
            task-types = {
                "book" = "Книга"
                "article" = "Статья"
                "podcast" = "Подкаст"
                "video" = "Видео"
                "course" = "Курс"
            }
        },
        {
            code = "en",
            name = "English"
            task-status = {
                "in-progress": "In progress"
                "planned": "Planned"
                "backlog": "Backlog"
                "completed": "Completed"
            }
            task-types = {
                "book" = "Book"
                "article" = "Article"
                "podcast" = "Podcast"
                "video" = "Video"
                "course" = "Course"
            }
        }

    ]
}